default:
    extension: .xccolortheme
    output: Themes
    nice-filename: true
    font-sans: FiraSans-Regular
    font-sans-bold: FiraSans-Bold
    font-sans-italic: FiraSans-Italic
    font-mono: FiraCodeRoman-Regular
    font-mono-bold: FiraCodeRoman-Bold
    font-mono-semibold: FiraCodeRoman-SemiBold
    font-size: 12.0
    font-size-small: 10.0
    font-size-h1: 24.0
    font-size-h2: 18.0
    font-size-h3: 14.0
    line-spacing: 1.1
