default:
    extension: .xccolortheme
    output: Themes
    no-prefix: true
    nice-filename: true
    font-sans: FiraSans-Regular
    font-sans-bold: FiraSans-Bold
    font-sans-italic: FiraSans-Italic
    font-mono: FiraCode-Retina
    font-mono-bold: FiraCodeRoman-Bold
    font-mono-semibold: FiraCodeRoman-SemiBold
