default:
    extension: .xccolortheme
    output: Themes
    font-face: FiraSans
    font-face-mono: FiraCodeRoman
    font-style: Regular
    font-style-bold: Bold
    font-style-semibold: SemiBold
    font-style-italic: Italic
